name: code-coverage


on: ["push"]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    name: code-coverage
    steps:
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
