name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Install dependencies
      run: npm ci
        
    - name: Run Jest
      run: npm run test __test__/ui.test.js
