name: Testing and Coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run Jest Puppeteer
        working-directory: __test__
        run: npm run coverage

      #     - uses: romeovs/lcov-reporter-action@v0.2.16
      #       with:
      #         lcov-file: ./coverage/lcov.info
      - run: yarn install
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: npm run --coverage
