name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: npm ci
        
    - name: Run Jest Puppeteer
      working-directory: __test__
      run: npm run coverage
      
#     - uses: romeovs/lcov-reporter-action@v0.2.16
#       with:
#         lcov-file: ./coverage/lcov.info
    - uses: ziishaned/jest-reporter-action@0.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: __test__
        test-command: "npm run coverage"

